FROM python:3.5
ENV PYTHONUNBUFFERED 1
ENV REDIS_HOST "redis"
ENV DJANGO_SETTINGS_MODULE "liveblog.settings.redis"
RUN mkdir /code
WORKDIR /code
ADD . /code/
RUN pip install -r requirements/redis.txt
RUN python manage.py migrate
